# Generated by Django 4.0.4 on 2022-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=120)),
                ('income', models.PositiveIntegerField(max_length=15)),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
    ]
