# Generated by Django 4.0.4 on 2022-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.PositiveIntegerField(),
        ),
    ]
